---

# Variables for deploying binaries into a JBoss server in domain mode
pkg_mgmt_root_url: "https://devops.my/libs-release-local"

docker_container_name: "jboss7"

docker_container_jboss_cli_path: "/opt/jboss/bin"

docker_host_jboss_deployment_path: "/tmp"

docker_container_jboss_deployment_path: "/tmp"

binaries:
  - { finalBinariesName: "devopsmy.war", backupBinariesName: "devopsmy.war.bak{{ lookup('pipe','date +%Y%m%d-%H%M%S') }}", binariesLocation: "{{ pkg_mgmt_root_url }}/devopsmy.war", isDeploy: "{{ is_devopsmy_war_deployment }}" }
  - { finalBinariesName: "devopsmy.jar", backupBinariesName: "devopsmy.jar.bak{{ lookup('pipe','date +%Y%m%d-%H%M%S') }}", binariesLocation: "{{ pkg_mgmt_root_url }}/devopsmy.jar", isDeploy: "{{ is_devopsmy_jar_deployment }}" }
