---

# This playbook will deploy binaries in JBoss for standalone, domain or docker scope

- hosts: {{ env }}
  roles:
    - role: deploy-bunaries-standalone
      when: scope == "standalone"

    - role: deploy-binaries-domain
      when: scope == "domain"

    - role: deploy-binaries-docker
      when: scope == "docker"
  vars_files:
    - group_vars/all/deploy-binaries/{{ scope }}.yml
